import type { Metadata } from "next";
import { Hanken_Grotesk, IBM_Plex_Mono, Lora } from "next/font/google";
import "@/styles/global.css";
import { Noise } from "@/components/backgrounds/noise";
import { GridLines } from "@/components/backgrounds/grid-lines";
import { Nav } from "@/components/nav";
import { Footer } from "@/components/footer";
import { ThemeProvider } from "@/components/theme-provider";

const hankenGrotesk = Hanken_Grotesk({
    variable: "--font-hanken-grotesk",
    subsets: ["latin"],
    weight: ["500"],
});

const ibmPlexMono = IBM_Plex_Mono({
    variable: "--font-ibm-plex-mono",
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
});

const lora = Lora({
    variable: "--font-lora",
    subsets: ["latin"],
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`relative transition-colors duration-300 ease-out ${hankenGrotesk.variable} ${ibmPlexMono.variable} ${lora.variable} antialiased`}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <Noise />
                    <GridLines />
                    <div className="min-h-dvh w-full flex flex-col mx-auto max-w-3xl px-4 py-8 gap-8 font-sans">
                        <Nav />
                        <main className="flex-grow">{children}</main>
                        <Footer />
                    </div>
                </ThemeProvider>
            </body>
        </html>
    );
}

export const metadata: Metadata = {
    title: "damitzi",
    description: "Generated by create next app",
};
